// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// AuditTrail is an object representing the database table.
type AuditTrail struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClientID  int64     `boil:"client_id" json:"client_id" toml:"client_id" yaml:"client_id"`
	Change    string    `boil:"change" json:"change" toml:"change" yaml:"change"`
	RoleUsed  string    `boil:"role_used" json:"role_used" toml:"role_used" yaml:"role_used"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *auditTrailR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L auditTrailL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AuditTrailColumns = struct {
	ID        string
	ClientID  string
	Change    string
	RoleUsed  string
	CreatedAt string
}{
	ID:        "id",
	ClientID:  "client_id",
	Change:    "change",
	RoleUsed:  "role_used",
	CreatedAt: "created_at",
}

// Generated where

var AuditTrailWhere = struct {
	ID        whereHelperint64
	ClientID  whereHelperint64
	Change    whereHelperstring
	RoleUsed  whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: `id`},
	ClientID:  whereHelperint64{field: `client_id`},
	Change:    whereHelperstring{field: `change`},
	RoleUsed:  whereHelperstring{field: `role_used`},
	CreatedAt: whereHelpertime_Time{field: `created_at`},
}

// AuditTrailRels is where relationship names are stored.
var AuditTrailRels = struct {
	Client string
}{
	Client: "Client",
}

// auditTrailR is where relationships are stored.
type auditTrailR struct {
	Client *Client
}

// NewStruct creates a new relationship struct
func (*auditTrailR) NewStruct() *auditTrailR {
	return &auditTrailR{}
}

// auditTrailL is where Load methods for each relationship are stored.
type auditTrailL struct{}

var (
	auditTrailColumns               = []string{"id", "client_id", "change", "role_used", "created_at"}
	auditTrailColumnsWithoutDefault = []string{}
	auditTrailColumnsWithDefault    = []string{"id", "client_id", "change", "role_used", "created_at"}
	auditTrailPrimaryKeyColumns     = []string{"id"}
)

type (
	// AuditTrailSlice is an alias for a slice of pointers to AuditTrail.
	// This should generally be used opposed to []AuditTrail.
	AuditTrailSlice []*AuditTrail
	// AuditTrailHook is the signature for custom AuditTrail hook methods
	AuditTrailHook func(context.Context, boil.ContextExecutor, *AuditTrail) error

	auditTrailQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	auditTrailType                 = reflect.TypeOf(&AuditTrail{})
	auditTrailMapping              = queries.MakeStructMapping(auditTrailType)
	auditTrailPrimaryKeyMapping, _ = queries.BindMapping(auditTrailType, auditTrailMapping, auditTrailPrimaryKeyColumns)
	auditTrailInsertCacheMut       sync.RWMutex
	auditTrailInsertCache          = make(map[string]insertCache)
	auditTrailUpdateCacheMut       sync.RWMutex
	auditTrailUpdateCache          = make(map[string]updateCache)
	auditTrailUpsertCacheMut       sync.RWMutex
	auditTrailUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var auditTrailBeforeInsertHooks []AuditTrailHook
var auditTrailBeforeUpdateHooks []AuditTrailHook
var auditTrailBeforeDeleteHooks []AuditTrailHook
var auditTrailBeforeUpsertHooks []AuditTrailHook

var auditTrailAfterInsertHooks []AuditTrailHook
var auditTrailAfterSelectHooks []AuditTrailHook
var auditTrailAfterUpdateHooks []AuditTrailHook
var auditTrailAfterDeleteHooks []AuditTrailHook
var auditTrailAfterUpsertHooks []AuditTrailHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AuditTrail) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AuditTrail) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AuditTrail) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AuditTrail) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AuditTrail) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AuditTrail) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AuditTrail) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AuditTrail) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AuditTrail) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditTrailAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAuditTrailHook registers your hook function for all future operations.
func AddAuditTrailHook(hookPoint boil.HookPoint, auditTrailHook AuditTrailHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		auditTrailBeforeInsertHooks = append(auditTrailBeforeInsertHooks, auditTrailHook)
	case boil.BeforeUpdateHook:
		auditTrailBeforeUpdateHooks = append(auditTrailBeforeUpdateHooks, auditTrailHook)
	case boil.BeforeDeleteHook:
		auditTrailBeforeDeleteHooks = append(auditTrailBeforeDeleteHooks, auditTrailHook)
	case boil.BeforeUpsertHook:
		auditTrailBeforeUpsertHooks = append(auditTrailBeforeUpsertHooks, auditTrailHook)
	case boil.AfterInsertHook:
		auditTrailAfterInsertHooks = append(auditTrailAfterInsertHooks, auditTrailHook)
	case boil.AfterSelectHook:
		auditTrailAfterSelectHooks = append(auditTrailAfterSelectHooks, auditTrailHook)
	case boil.AfterUpdateHook:
		auditTrailAfterUpdateHooks = append(auditTrailAfterUpdateHooks, auditTrailHook)
	case boil.AfterDeleteHook:
		auditTrailAfterDeleteHooks = append(auditTrailAfterDeleteHooks, auditTrailHook)
	case boil.AfterUpsertHook:
		auditTrailAfterUpsertHooks = append(auditTrailAfterUpsertHooks, auditTrailHook)
	}
}

// One returns a single auditTrail record from the query.
func (q auditTrailQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AuditTrail, error) {
	o := &AuditTrail{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for audit_trails")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AuditTrail records from the query.
func (q auditTrailQuery) All(ctx context.Context, exec boil.ContextExecutor) (AuditTrailSlice, error) {
	var o []*AuditTrail

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AuditTrail slice")
	}

	if len(auditTrailAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AuditTrail records in the query.
func (q auditTrailQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count audit_trails rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q auditTrailQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if audit_trails exists")
	}

	return count > 0, nil
}

// Client pointed to by the foreign key.
func (o *AuditTrail) Client(mods ...qm.QueryMod) clientQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ClientID),
	}

	queryMods = append(queryMods, mods...)

	query := Clients(queryMods...)
	queries.SetFrom(query.Query, "\"clients\"")

	return query
}

// LoadClient allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (auditTrailL) LoadClient(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuditTrail interface{}, mods queries.Applicator) error {
	var slice []*AuditTrail
	var object *AuditTrail

	if singular {
		object = maybeAuditTrail.(*AuditTrail)
	} else {
		slice = *maybeAuditTrail.(*[]*AuditTrail)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &auditTrailR{}
		}
		args = append(args, object.ClientID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &auditTrailR{}
			}

			for _, a := range args {
				if a == obj.ClientID {
					continue Outer
				}
			}

			args = append(args, obj.ClientID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`clients`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Client")
	}

	var resultSlice []*Client
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Client")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for clients")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for clients")
	}

	if len(auditTrailAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Client = foreign
		if foreign.R == nil {
			foreign.R = &clientR{}
		}
		foreign.R.AuditTrails = append(foreign.R.AuditTrails, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClientID == foreign.ID {
				local.R.Client = foreign
				if foreign.R == nil {
					foreign.R = &clientR{}
				}
				foreign.R.AuditTrails = append(foreign.R.AuditTrails, local)
				break
			}
		}
	}

	return nil
}

// SetClient of the auditTrail to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.AuditTrails.
func (o *AuditTrail) SetClient(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Client) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"audit_trails\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"client_id"}),
		strmangle.WhereClause("\"", "\"", 0, auditTrailPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClientID = related.ID
	if o.R == nil {
		o.R = &auditTrailR{
			Client: related,
		}
	} else {
		o.R.Client = related
	}

	if related.R == nil {
		related.R = &clientR{
			AuditTrails: AuditTrailSlice{o},
		}
	} else {
		related.R.AuditTrails = append(related.R.AuditTrails, o)
	}

	return nil
}

// AuditTrails retrieves all the records using an executor.
func AuditTrails(mods ...qm.QueryMod) auditTrailQuery {
	mods = append(mods, qm.From("\"audit_trails\""))
	return auditTrailQuery{NewQuery(mods...)}
}

// FindAuditTrail retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAuditTrail(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*AuditTrail, error) {
	auditTrailObj := &AuditTrail{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"audit_trails\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, auditTrailObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from audit_trails")
	}

	return auditTrailObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AuditTrail) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no audit_trails provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(auditTrailColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	auditTrailInsertCacheMut.RLock()
	cache, cached := auditTrailInsertCache[key]
	auditTrailInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			auditTrailColumns,
			auditTrailColumnsWithDefault,
			auditTrailColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(auditTrailType, auditTrailMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(auditTrailType, auditTrailMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"audit_trails\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"audit_trails\" () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT \"%s\" FROM \"audit_trails\" WHERE %s", strings.Join(returnColumns, "\",\""), strmangle.WhereClause("\"", "\"", 0, auditTrailPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into audit_trails")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == auditTrailMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for audit_trails")
	}

CacheNoHooks:
	if !cached {
		auditTrailInsertCacheMut.Lock()
		auditTrailInsertCache[key] = cache
		auditTrailInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AuditTrail.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AuditTrail) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	auditTrailUpdateCacheMut.RLock()
	cache, cached := auditTrailUpdateCache[key]
	auditTrailUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			auditTrailColumns,
			auditTrailPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update audit_trails, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"audit_trails\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, auditTrailPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(auditTrailType, auditTrailMapping, append(wl, auditTrailPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update audit_trails row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for audit_trails")
	}

	if !cached {
		auditTrailUpdateCacheMut.Lock()
		auditTrailUpdateCache[key] = cache
		auditTrailUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q auditTrailQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for audit_trails")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for audit_trails")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AuditTrailSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditTrailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"audit_trails\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, auditTrailPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in auditTrail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all auditTrail")
	}
	return rowsAff, nil
}

// Delete deletes a single AuditTrail record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AuditTrail) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AuditTrail provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), auditTrailPrimaryKeyMapping)
	sql := "DELETE FROM \"audit_trails\" WHERE \"id\"=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from audit_trails")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for audit_trails")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q auditTrailQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no auditTrailQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from audit_trails")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for audit_trails")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AuditTrailSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AuditTrail slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(auditTrailBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditTrailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"audit_trails\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, auditTrailPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from auditTrail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for audit_trails")
	}

	if len(auditTrailAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AuditTrail) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAuditTrail(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuditTrailSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AuditTrailSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditTrailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"audit_trails\".* FROM \"audit_trails\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, auditTrailPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AuditTrailSlice")
	}

	*o = slice

	return nil
}

// AuditTrailExists checks if the AuditTrail row exists.
func AuditTrailExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"audit_trails\" where \"id\"=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if audit_trails exists")
	}

	return exists, nil
}
