// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuditTrails                  string
	ClientKeys                   string
	ClientOrderHistory           string
	ClientRoles                  string
	Clients                      string
	ExchangePlatformTradeHistory string
	Exchanges                    string
	Keys                         string
	RoleKeys                     string
	Roles                        string
}{
	AuditTrails:                  "audit_trails",
	ClientKeys:                   "client_keys",
	ClientOrderHistory:           "client_order_history",
	ClientRoles:                  "client_roles",
	Clients:                      "clients",
	ExchangePlatformTradeHistory: "exchange_platform_trade_history",
	Exchanges:                    "exchanges",
	Keys:                         "keys",
	RoleKeys:                     "role_keys",
	Roles:                        "roles",
}
