// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessControls               string
	AuditTrails                  string
	ClientOrderHistory           string
	Clients                      string
	ExchangePlatformTradeHistory string
	Exchanges                    string
	Keys                         string
}{
	AccessControls:               "access_controls",
	AuditTrails:                  "audit_trails",
	ClientOrderHistory:           "client_order_history",
	Clients:                      "clients",
	ExchangePlatformTradeHistory: "exchange_platform_trade_history",
	Exchanges:                    "exchanges",
	Keys:                         "keys",
}
