// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// ClientKey is an object representing the database table.
type ClientKey struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	KeyID     int64     `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	ClientID  int64     `boil:"client_id" json:"client_id" toml:"client_id" yaml:"client_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *clientKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L clientKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ClientKeyColumns = struct {
	ID        string
	KeyID     string
	ClientID  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	KeyID:     "key_id",
	ClientID:  "client_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

var ClientKeyWhere = struct {
	ID        whereHelperint64
	KeyID     whereHelperint64
	ClientID  whereHelperint64
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: `id`},
	KeyID:     whereHelperint64{field: `key_id`},
	ClientID:  whereHelperint64{field: `client_id`},
	CreatedAt: whereHelpertime_Time{field: `created_at`},
	UpdatedAt: whereHelpertime_Time{field: `updated_at`},
}

// ClientKeyRels is where relationship names are stored.
var ClientKeyRels = struct {
	Key    string
	Client string
}{
	Key:    "Key",
	Client: "Client",
}

// clientKeyR is where relationships are stored.
type clientKeyR struct {
	Key    *Key
	Client *Client
}

// NewStruct creates a new relationship struct
func (*clientKeyR) NewStruct() *clientKeyR {
	return &clientKeyR{}
}

// clientKeyL is where Load methods for each relationship are stored.
type clientKeyL struct{}

var (
	clientKeyColumns               = []string{"id", "key_id", "client_id", "created_at", "updated_at"}
	clientKeyColumnsWithoutDefault = []string{}
	clientKeyColumnsWithDefault    = []string{"id", "key_id", "client_id", "created_at", "updated_at"}
	clientKeyPrimaryKeyColumns     = []string{"id"}
)

type (
	// ClientKeySlice is an alias for a slice of pointers to ClientKey.
	// This should generally be used opposed to []ClientKey.
	ClientKeySlice []*ClientKey
	// ClientKeyHook is the signature for custom ClientKey hook methods
	ClientKeyHook func(context.Context, boil.ContextExecutor, *ClientKey) error

	clientKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	clientKeyType                 = reflect.TypeOf(&ClientKey{})
	clientKeyMapping              = queries.MakeStructMapping(clientKeyType)
	clientKeyPrimaryKeyMapping, _ = queries.BindMapping(clientKeyType, clientKeyMapping, clientKeyPrimaryKeyColumns)
	clientKeyInsertCacheMut       sync.RWMutex
	clientKeyInsertCache          = make(map[string]insertCache)
	clientKeyUpdateCacheMut       sync.RWMutex
	clientKeyUpdateCache          = make(map[string]updateCache)
	clientKeyUpsertCacheMut       sync.RWMutex
	clientKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var clientKeyBeforeInsertHooks []ClientKeyHook
var clientKeyBeforeUpdateHooks []ClientKeyHook
var clientKeyBeforeDeleteHooks []ClientKeyHook
var clientKeyBeforeUpsertHooks []ClientKeyHook

var clientKeyAfterInsertHooks []ClientKeyHook
var clientKeyAfterSelectHooks []ClientKeyHook
var clientKeyAfterUpdateHooks []ClientKeyHook
var clientKeyAfterDeleteHooks []ClientKeyHook
var clientKeyAfterUpsertHooks []ClientKeyHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ClientKey) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ClientKey) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ClientKey) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ClientKey) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ClientKey) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ClientKey) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ClientKey) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ClientKey) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ClientKey) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range clientKeyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddClientKeyHook registers your hook function for all future operations.
func AddClientKeyHook(hookPoint boil.HookPoint, clientKeyHook ClientKeyHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		clientKeyBeforeInsertHooks = append(clientKeyBeforeInsertHooks, clientKeyHook)
	case boil.BeforeUpdateHook:
		clientKeyBeforeUpdateHooks = append(clientKeyBeforeUpdateHooks, clientKeyHook)
	case boil.BeforeDeleteHook:
		clientKeyBeforeDeleteHooks = append(clientKeyBeforeDeleteHooks, clientKeyHook)
	case boil.BeforeUpsertHook:
		clientKeyBeforeUpsertHooks = append(clientKeyBeforeUpsertHooks, clientKeyHook)
	case boil.AfterInsertHook:
		clientKeyAfterInsertHooks = append(clientKeyAfterInsertHooks, clientKeyHook)
	case boil.AfterSelectHook:
		clientKeyAfterSelectHooks = append(clientKeyAfterSelectHooks, clientKeyHook)
	case boil.AfterUpdateHook:
		clientKeyAfterUpdateHooks = append(clientKeyAfterUpdateHooks, clientKeyHook)
	case boil.AfterDeleteHook:
		clientKeyAfterDeleteHooks = append(clientKeyAfterDeleteHooks, clientKeyHook)
	case boil.AfterUpsertHook:
		clientKeyAfterUpsertHooks = append(clientKeyAfterUpsertHooks, clientKeyHook)
	}
}

// One returns a single clientKey record from the query.
func (q clientKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ClientKey, error) {
	o := &ClientKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for client_keys")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ClientKey records from the query.
func (q clientKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (ClientKeySlice, error) {
	var o []*ClientKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ClientKey slice")
	}

	if len(clientKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ClientKey records in the query.
func (q clientKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count client_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q clientKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if client_keys exists")
	}

	return count > 0, nil
}

// Key pointed to by the foreign key.
func (o *ClientKey) Key(mods ...qm.QueryMod) keyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.KeyID),
	}

	queryMods = append(queryMods, mods...)

	query := Keys(queryMods...)
	queries.SetFrom(query.Query, "\"keys\"")

	return query
}

// Client pointed to by the foreign key.
func (o *ClientKey) Client(mods ...qm.QueryMod) clientQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ClientID),
	}

	queryMods = append(queryMods, mods...)

	query := Clients(queryMods...)
	queries.SetFrom(query.Query, "\"clients\"")

	return query
}

// LoadKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (clientKeyL) LoadKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClientKey interface{}, mods queries.Applicator) error {
	var slice []*ClientKey
	var object *ClientKey

	if singular {
		object = maybeClientKey.(*ClientKey)
	} else {
		slice = *maybeClientKey.(*[]*ClientKey)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &clientKeyR{}
		}
		args = append(args, object.KeyID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &clientKeyR{}
			}

			for _, a := range args {
				if a == obj.KeyID {
					continue Outer
				}
			}

			args = append(args, obj.KeyID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`keys`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Key")
	}

	var resultSlice []*Key
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Key")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for keys")
	}

	if len(clientKeyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Key = foreign
		if foreign.R == nil {
			foreign.R = &keyR{}
		}
		foreign.R.ClientKeys = append(foreign.R.ClientKeys, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KeyID == foreign.ID {
				local.R.Key = foreign
				if foreign.R == nil {
					foreign.R = &keyR{}
				}
				foreign.R.ClientKeys = append(foreign.R.ClientKeys, local)
				break
			}
		}
	}

	return nil
}

// LoadClient allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (clientKeyL) LoadClient(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClientKey interface{}, mods queries.Applicator) error {
	var slice []*ClientKey
	var object *ClientKey

	if singular {
		object = maybeClientKey.(*ClientKey)
	} else {
		slice = *maybeClientKey.(*[]*ClientKey)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &clientKeyR{}
		}
		args = append(args, object.ClientID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &clientKeyR{}
			}

			for _, a := range args {
				if a == obj.ClientID {
					continue Outer
				}
			}

			args = append(args, obj.ClientID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`clients`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Client")
	}

	var resultSlice []*Client
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Client")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for clients")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for clients")
	}

	if len(clientKeyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Client = foreign
		if foreign.R == nil {
			foreign.R = &clientR{}
		}
		foreign.R.ClientKeys = append(foreign.R.ClientKeys, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClientID == foreign.ID {
				local.R.Client = foreign
				if foreign.R == nil {
					foreign.R = &clientR{}
				}
				foreign.R.ClientKeys = append(foreign.R.ClientKeys, local)
				break
			}
		}
	}

	return nil
}

// SetKey of the clientKey to the related item.
// Sets o.R.Key to related.
// Adds o to related.R.ClientKeys.
func (o *ClientKey) SetKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Key) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"client_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"key_id"}),
		strmangle.WhereClause("\"", "\"", 0, clientKeyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KeyID = related.ID
	if o.R == nil {
		o.R = &clientKeyR{
			Key: related,
		}
	} else {
		o.R.Key = related
	}

	if related.R == nil {
		related.R = &keyR{
			ClientKeys: ClientKeySlice{o},
		}
	} else {
		related.R.ClientKeys = append(related.R.ClientKeys, o)
	}

	return nil
}

// SetClient of the clientKey to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.ClientKeys.
func (o *ClientKey) SetClient(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Client) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"client_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"client_id"}),
		strmangle.WhereClause("\"", "\"", 0, clientKeyPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClientID = related.ID
	if o.R == nil {
		o.R = &clientKeyR{
			Client: related,
		}
	} else {
		o.R.Client = related
	}

	if related.R == nil {
		related.R = &clientR{
			ClientKeys: ClientKeySlice{o},
		}
	} else {
		related.R.ClientKeys = append(related.R.ClientKeys, o)
	}

	return nil
}

// ClientKeys retrieves all the records using an executor.
func ClientKeys(mods ...qm.QueryMod) clientKeyQuery {
	mods = append(mods, qm.From("\"client_keys\""))
	return clientKeyQuery{NewQuery(mods...)}
}

// FindClientKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindClientKey(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ClientKey, error) {
	clientKeyObj := &ClientKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"client_keys\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, clientKeyObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from client_keys")
	}

	return clientKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ClientKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no client_keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(clientKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	clientKeyInsertCacheMut.RLock()
	cache, cached := clientKeyInsertCache[key]
	clientKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			clientKeyColumns,
			clientKeyColumnsWithDefault,
			clientKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(clientKeyType, clientKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(clientKeyType, clientKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"client_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"client_keys\" () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT \"%s\" FROM \"client_keys\" WHERE %s", strings.Join(returnColumns, "\",\""), strmangle.WhereClause("\"", "\"", 0, clientKeyPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into client_keys")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == clientKeyMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for client_keys")
	}

CacheNoHooks:
	if !cached {
		clientKeyInsertCacheMut.Lock()
		clientKeyInsertCache[key] = cache
		clientKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ClientKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ClientKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	clientKeyUpdateCacheMut.RLock()
	cache, cached := clientKeyUpdateCache[key]
	clientKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			clientKeyColumns,
			clientKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update client_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"client_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, clientKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(clientKeyType, clientKeyMapping, append(wl, clientKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update client_keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for client_keys")
	}

	if !cached {
		clientKeyUpdateCacheMut.Lock()
		clientKeyUpdateCache[key] = cache
		clientKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q clientKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for client_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for client_keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ClientKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), clientKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"client_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, clientKeyPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in clientKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all clientKey")
	}
	return rowsAff, nil
}

// Delete deletes a single ClientKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ClientKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ClientKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), clientKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"client_keys\" WHERE \"id\"=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from client_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for client_keys")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q clientKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no clientKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from client_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for client_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ClientKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ClientKey slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(clientKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), clientKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"client_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, clientKeyPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from clientKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for client_keys")
	}

	if len(clientKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ClientKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindClientKey(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ClientKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ClientKeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), clientKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"client_keys\".* FROM \"client_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, clientKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ClientKeySlice")
	}

	*o = slice

	return nil
}

// ClientKeyExists checks if the ClientKey row exists.
func ClientKeyExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"client_keys\" where \"id\"=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if client_keys exists")
	}

	return exists, nil
}
